### PR TITLE
style.md: Split into separate files

### PR DESCRIPTION
**Pull request by abhinav**
Splits style.md into separate files
and stitches them back together with [stitchmd].

  [stitchmd]: https://github.com/abhinav/stitchmd

This makes it easier to manage the many sections of the style guide.
The src files are independently browseable
but this also keeps the final style.md with its old headers
so that existing users who link to it aren't broken.

Differences in style.md:

- *Prefer Specifying Container Capacity* no longer has its subitems
  listed in the table of contents.
  This is because those are part of the same document;
  the header itself doesn't have much content.
  This is fixable if desirable by either removing the content under the
  header, or by moving the slice and map sections into separate files.
  I chose the current configuration because it seemed fine as-is.
- All links have been converted to inline `[..](https://...)` style
  in the generated Markdown,
  but will be left alone in the input.
  This doesn't change how GitHub interprets these in any way.
- Multi-line list items are aligned to the list item delimiter.
  Again, this doesn't change how GitHub interprets these.

https://github.com/uber-go/guide/pull/168/files#diff-7b1bca67f13234851df27465985cb475d4a9ad49dc48df87a620c19378ddf03c

For automation, this includes a Makefile with two targets:

- `make style.md` updates the style guide from src/.
- `make lint` verifies it's up to date.

It sets up a GitHub Workflow that'll run `make lint` in CI,
and dependabot to update the dependencies in tools/
and for the workflow, on a periodic basis.

Refs https://github.com/uber-go/guide/discussions/159

### CODE REVIEW

**Comment by abhinav** [comment]
@sywhang @mway FYI, I've split the PR into separate commits to make it (hopefully) easier to review.

**Review by r-hang — APPROVED** [review]

**Review by sywhang — APPROVED** [review]
LGTM. Thanks for working on this!

**Comment by joaolbarba88** [comment]
Desbloquear

**Comment by joaolbarba88** [comment]
Uber

**Comment by joaolbarba88** [comment]
https://github.com/vorobeyme/uber-go-style-guide-uk/pull/3#issue-2092805948 de

**Pull request merged**
