### PR TITLE
Add link to Japanese

### PR DESCRIPTION
**Pull request by knsh14**
I translated this great guide into Japanese.
so I want you to add link to my work.

### CODE REVIEW

**Comment by abhinav** [comment]
@knsh14 sorry, would you mind rebasing as well? Thanks!

**Comment by TangoEnSkai** [comment]
Just for your information, other translation is following this style.
```
中文翻译 (Chinese): xxjwxc/uber_go_guide_cn
한국어 번역 (Korean): TangoEnSkai/uber-go-style-guide-kr
```

You may change your link's title as `日本語訳 (Japanese):`

**Comment by knsh14** [comment]
@TangoEnSkai thanks for your information! I will fix like that.

**Comment by knsh14** [comment]
@abhinav thanks for your comment! just fixed.

**Comment by mway** [comment]
Thanks folks!

**Pull request merged**
